#%% raw
%%plantuml

@startuml


database "VectorStore"{
    object rag_vectorstore
object chroma_vectorstore
}

package "Retriever" {
    object rag_retriever
object multi_query_retriever
object merge_retriever
object self_retriever
object summary_retriever

summary_retriever --> chroma_vectorstore
rag_vectorstore --> chroma_vectorstore
self_retriever -> rag_retriever
rag_retriever --> rag_vectorstore
merge_retriever -> summary_retriever
merge_retriever -> self_retriever
multi_query_retriever -> merge_retriever
}

@enduml